apiVersion: flux.kluctl.io/v1alpha1
kind: KluctlDeployment
metadata:
  name: klu-simple-helm
spec:
  interval: 60m
  source:
    url: https://github.com/kluctl/kluctl-examples.git
    path: "./microservices-demo/3-templating-and-multi-env/"
  timeout: 2m
  target: prod
  context: default
  prune: true
  delete: true